[server]
enableStaticServing = true

[theme]
base = "dark"
baseFontSize = 15
primaryColor = "skyblue"
backgroundColor = "#121212"
secondaryBackgroundColor = "#333333"
textColor = "#FFFFFF"
linkColor = "#9D9D9D"
borderColor = "#7F7F7F"
showWidgetBorder = false
baseRadius = "0.3rem"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#000000"
secondaryBackgroundColor = "#333333"
borderColor = "#696969" 